# Python Doesn't Have Good Numeric Support
* Python integers are actually an object with header and typing information
* access to Python integers requires a level of indirection
* In C, integers are directly accessible in memory without indirection
<img src="images/python-01.png" width=400 height=400>

## The Problem is Even Worse for Python Lists 
* Python lists are immensely flexible
  * no fixed size
  * OK to have heterogeneous data
* ...but as a result they are not likely to be contiguous in memory
* and even if they are, there is still a lot of indirection required
* ergo, they aren't good for fast number crunching
<img src="images/python-02.png" width=400 height=400>

## The Solution is to Use <a href="http://www.numpy.org">Numpy</a>
* written in C
* allows for vectorized operations

In [5]:
import numpy as np
np.random.seed(0)

# let's create a simple Python function which
# computes 1/x for a list of values
def compute_reciprocals(values):
    # first, create an empty numpy array
    output = np.empty(len(values))
    # now fill it...
    for i in range(len(values)):
        output[i] = 1.0 / values[i]

    return output

values = np.random.randint(1, 10, size=5)
print(values, type(values))
compute_reciprocals(values)

[6 1 4 4 8] <class 'numpy.ndarray'>


array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [6]:
# Doing something like the above is super slow in Python
big_array = np.random.randint(1, 100, size=1_000_000)
%timeit compute_reciprocals(big_array) # time this code (this line)

611 ms ± 6.07 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
x = 2.345
x - 2.345

0.0

In [8]:
x - 2.345 == 0.0

True

In [9]:
.1 + .1 + .1 # see IEEE 754

0.30000000000000004

In [10]:
total = .1 + .1 + .1
print(f'{total:.10f}')

0.3000000000


## __np.trunc()__

* nearest integer __`i`__ which is closer to zero than __`x`__ is

In [16]:
np.trunc(x)

np.float64(2.0)

## __np.floor()__

* the largest integer __`i`__, such that __`i <= x`__

In [19]:
np.floor(x)

np.float64(2.0)

In [13]:
np.floor(2.01)

np.float64(2.0)

In [14]:
np.floor(2.00)

np.float64(2.0)

## __np.ceil()__

* the smallest integer __`i`__, such that __`i >= x`__

In [21]:
np.ceil(x)

np.float64(-2.0)

In [22]:
np.ceil(2.01)

np.float64(3.0)

In [23]:
np.ceil(2.0)

np.float64(2.0)

In [24]:
np.ceil(x) - 1

np.float64(2.0)

In [25]:
np.ceil(2.01) - 1

np.float64(2.0)

## A numpy Array
* data is contiguous
<img src="images/python-03.png" width=300 height=300>

In [26]:
# numpy will intuit the data type
a = np.array([1, 4, 2, 5, 3])
a, a.dtype

(array([1, 4, 2, 5, 3]), dtype('int64'))

In [27]:
a = np.array([3.14, 4, 2, 3])
a, a.dtype

(array([3.14, 4.  , 2.  , 3.  ]), dtype('float64'))

In [28]:
# ...or you can be explicit
a = np.array([1, 2, 3, 4], dtype='float32')
a

array([1., 2., 3., 4.], dtype=float32)

In [30]:
twodarray = np.array([range(i, i + 3) for i in [2, 4, 6]])
print(twodarray, type(twodarray))

[[2 3 4]
 [4 5 6]
 [6 7 8]] <class 'numpy.ndarray'>


In [31]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.full((3, 5), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [34]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [39]:
np.random.random((3, 3))

array([[0.25241011, 0.97572458, 0.1197632 ],
       [0.20856888, 0.23983126, 0.39034023],
       [0.61318864, 0.8603706 , 0.34645385]])

In [41]:
np.random.normal(0, 1, (3, 3))

array([[-0.80846432, -1.55328005,  1.09581535],
       [ 1.0034082 , -0.96307811,  0.38494418],
       [-2.10187333,  0.43009583, -0.66377698]])

In [43]:
np.random.randint(0, 10, (3, 3))

array([[1, 8, 6],
       [9, 9, 7],
       [6, 0, 9]])

In [44]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Converting array types

In [45]:
x = np.linspace(0, 10, 50)
x

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [46]:
x.astype(int)

array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,
        3,  3,  3,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  6,
        6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9, 10])

## Multi-dimensional Arrays

In [47]:
x2 = np.random.randint(10, size=(3, 4))
x2

array([[1, 1, 3, 9],
       [2, 6, 1, 1],
       [7, 8, 9, 5]])

## True "matrix-style" indexing

In [48]:
x2[0, 0]

np.int64(1)

In [49]:
x2[2, 0]

np.int64(7)

In [50]:
x2[2, -1]

np.int64(5)

In [51]:
x2[0, 0] = 12
x2

array([[12,  1,  3,  9],
       [ 2,  6,  1,  1],
       [ 7,  8,  9,  5]])

In [54]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Array Slicing

In [55]:
x = np.arange(10)
x[:5] # Pythonic ... "first 5"

array([0, 1, 2, 3, 4])

In [56]:
x[5:]

array([5, 6, 7, 8, 9])

In [57]:
x[4:7]

array([4, 5, 6])

In [58]:
x[::2]

array([0, 2, 4, 6, 8])

In [59]:
x[1::2]

array([1, 3, 5, 7, 9])

In [60]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [64]:
x[5::-2]

array([5, 3, 1])

## Filtering 1-dimensional data

In [66]:
x = np.array([ 1, 0, 5, 2, 1, 0, 8, 0, 0 ])
x

array([1, 0, 5, 2, 1, 0, 8, 0, 0])

In [67]:
np.nonzero(x)

(array([0, 2, 3, 4, 6]),)

In [68]:
x[np.nonzero(x)]

array([1, 5, 2, 1, 8])

In [69]:
x[x < 3]

array([1, 0, 2, 1, 0, 0, 0])

## Filtering 2-dimensional data

In [70]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, -1, 0]])
x

array([[ 3,  0,  0],
       [ 0,  4,  0],
       [ 5, -1,  0]])

In [71]:
# produces two arrays, one with x coords, one with y coords
np.nonzero(x)

(array([0, 1, 2, 2]), array([0, 1, 0, 1]))

In [72]:
x[np.nonzero(x)]

array([ 3,  4,  5, -1])

In [73]:
np.transpose(np.nonzero(x))

array([[0, 0],
       [1, 1],
       [2, 0],
       [2, 1]])

## Multi-dimensional subarrays

In [74]:
x2

array([[12,  1,  3,  9],
       [ 2,  6,  1,  1],
       [ 7,  8,  9,  5]])

In [75]:
x2[:2, :3]

array([[12,  1,  3],
       [ 2,  6,  1]])

In [76]:
x2[:, ::2]

array([[12,  3],
       [ 2,  1],
       [ 7,  9]])

In [77]:
x2[::-1, ::-1]

array([[ 5,  9,  8,  7],
       [ 1,  1,  6,  2],
       [ 9,  3,  1, 12]])

In [80]:
np.flip(np.flip(x2, axis=0), axis=1)

array([[ 5,  9,  8,  7],
       [ 1,  1,  6,  2],
       [ 9,  3,  1, 12]])

In [79]:
help(np.flip)

Help on _ArrayFunctionDispatcher in module numpy:

flip(m, axis=None)
    Reverse the order of elements in an array along the given axis.

    The shape of the array is preserved, but the elements are reordered.

    Parameters
    ----------
    m : array_like
        Input array.
    axis : None or int or tuple of ints, optional
         Axis or axes along which to flip over. The default,
         axis=None, will flip over all of the axes of the input array.
         If axis is negative it counts from the last to the first axis.

         If axis is a tuple of ints, flipping is performed on all of the axes
         specified in the tuple.

    Returns
    -------
    out : array_like
        A view of `m` with the entries of axis reversed.  Since a view is
        returned, this operation is done in constant time.

    See Also
    --------
    flipud : Flip an array vertically (axis=0).
    fliplr : Flip an array horizontally (axis=1).

    Notes
    -----
    flip(m, 0) is equivale

## Subarray Views

In [81]:
x2, id(x2)

(array([[12,  1,  3,  9],
        [ 2,  6,  1,  1],
        [ 7,  8,  9,  5]]),
 4786043664)

In [82]:
x2_sub = x2[:2, :2]
x2_sub, id(x2_sub)

(array([[12,  1],
        [ 2,  6]]),
 4812973296)

In [83]:
x2_sub[0, 0] = 99
x2_sub

array([[99,  1],
       [ 2,  6]])

In [84]:
x2 # changes x2 as well, since the subarray has references to the original

array([[99,  1,  3,  9],
       [ 2,  6,  1,  1],
       [ 7,  8,  9,  5]])

## Vectorized Operations

In [85]:
big_array = np.random.randint(1, 100, size=1_000_000)

In [ ]:
%timeit 1.0 / big_array

In [ ]:
big_array = np.random.rand(1_000_000)
%timeit sum(big_array) # Python sum method (serial)
%timeit np.sum(big_array) # numpy sum method (vectorized)

## Universal Funcs (ufuncs)
* operates on ndarrays in an element-by-element fashion
* _vectorized_ wrapper for a function that takes a fixed number of specific inputs and produces a fixed number of specific outputs

In [ ]:
x = np.arange(9).reshape((3, 3))
2 ** x

In [ ]:
x = np.arange(4)
-(0.5 * x + 1) ** 2

| Operator | ufunc           | Description                         |
|----------|-----------------|-------------------------------------|
|   +      | np.add          | Addition (e.g., 1 + 1 = 2)          |
|   -      | np.subtract     | Subtraction (e.g., 3 - 2 = 1)       |
|   -      | np.negative     | Unary negation (e.g., -2)           |
|   *      | np.multiply     | Multiplication (e.g., 2 * 3 = 6)    |
|   /      | np.divide       | Division (e.g., 3 / 2 = 1.5)        |
|   //     | np.floor_divide | Floor division (e.g., 3 // 2 = 1)   |
|   **     | np.power        | Exponentiation (e.g., 2 ** 3 = 8)   |
|   %      | np.mod          | Modulus/remainder (e.g., 9 % 4 = 1) |

## Exponent and Logarithm ufuncs

In [ ]:
x = [1, 2, 3]
np.exp(x)

In [ ]:
np.exp2(x)

In [ ]:
np.power(3, x)

In [ ]:
np.log([1, np.e, 3])

In [ ]:
np.log2([1, 256, 65536])

In [ ]:
np.log10([1_000, 1_000_000, 10 ** 10])

## Aggregate ufuncs

In [ ]:
x = np.arange(1, 6)
np.add.reduce(x) # reduce to scalar via addition

In [ ]:
np.multiply.reduce(x)

In [ ]:
np.add.accumulate(x)

In [ ]:
np.multiply.accumulate(x)